// resources/js/Pages/Welcome.vue
<script setup>
import {Head, Link} from '@inertiajs/vue3';
import AppLayout from '@/Layouts/AppLayout.vue';
import SideMenu from "@/Components/SideMenu.vue";


defineProps({
    canLogin: {
        type: Boolean,
    },
    canRegister: {
        type: Boolean,
    },
    laravelVersion: {
        type: String,
        required: true,
    },
    phpVersion: {
        type: String,
        required: true,
    },
});

function handleImageError() {
    document.getElementById('screenshot-container')?.classList.add('!hidden');
    document.getElementById('docs-card')?.classList.add('!row-span-1');
    document.getElementById('docs-card-content')?.classList.add('!flex-row');
    document.getElementById('background')?.classList.add('!hidden');
}
</script>

<template>
    <AppLayout>
        <Head title="Welcome"/>
        <SideMenu/>
    </AppLayout>
</template>

// resources/js/Pages/Welcome.tsx
// import PhotoWall from '@/components/photo-wall'
import SidebarCustom from '@/Components/SidebarCustom';
import General from '@/Layouts/General';
import { PageProps } from '@/types';
import { useState } from 'react';

export default function Welcome({
    auth,
}: PageProps<{ laravelVersion: string; phpVersion: string }>) {
    const [loggedIn, setLoggedIn] = useState(!!auth.user?.id);
    const handleImageError = () => {
        document
            .getElementById('screenshot-container')
            ?.classList.add('!hidden');
        document.getElementById('docs-card')?.classList.add('!row-span-1');
        document
            .getElementById('docs-card-content')
            ?.classList.add('!flex-row');
        document.getElementById('background')?.classList.add('!hidden');
    };

    return (
        <General>
            <SidebarCustom loggedIn={loggedIn} />
        </General>
    );
}
